-- Generated by SQL Maestro for MySQL. Release date 22.12.2012
-- 13.11.2013 11:30:29
-- ----------------------------------
-- Alias: ponty at localhost
-- Database name: ponty
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.6.12-log
-- Session ID: 46
-- Character set: latin1
-- Collation: latin1_swedish_ci


CREATE DATABASE ponty
  CHARACTER SET latin1
  COLLATE latin1_swedish_ci;

USE ponty;

/* Tables */
CREATE TABLE answers (
  id           int AUTO_INCREMENT NOT NULL,
  `text`       text,
  question_id  int,
  created      timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE api_keys (
  id                        bigint AUTO_INCREMENT NOT NULL,
  api_key                   varchar(255) NOT NULL,
  blocked                   tinyint DEFAULT '1',
  valid_until               timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  current_monthly_requests  bigint DEFAULT '0',
  max_monthly_requests      int,
  created                   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id                   int,
  app_name                  varchar(250) NOT NULL,
  app_link                  varchar(250) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE api_settings (
  id            int AUTO_INCREMENT NOT NULL,
  max_requests  bigint NOT NULL,
  valid_for     bigint NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE categories (
  id           int AUTO_INCREMENT NOT NULL,
  name         varchar(250) NOT NULL,
  visible      tinyint(1) DEFAULT '1',
  description  text,
  created      timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE questions (
  id            int AUTO_INCREMENT NOT NULL,
  public        tinyint(1) DEFAULT '0',
  name          varchar(250) NOT NULL,
  blocked       tinyint(1) DEFAULT '0',
  stack_id      int,
  category_id   int,
  rating        double DEFAULT '0',
  created       timestamp DEFAULT CURRENT_TIMESTAMP,
  rating_count  int DEFAULT '0',
  rating_sum    int DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE ratings (
  id            int AUTO_INCREMENT NOT NULL,
  user_id       int NOT NULL,
  question_id   int NOT NULL,
  rating_value  int NOT NULL,
  created       timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE stacks (
  id           int AUTO_INCREMENT NOT NULL,
  name         varchar(250) NOT NULL,
  description  text,
  user_id      int NOT NULL,
  created      timestamp DEFAULT CURRENT_TIMESTAMP,
  public       tinyint DEFAULT '0',
  publickey    varchar(45),
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE trash_mail_providers (
  id       int AUTO_INCREMENT NOT NULL,
  address  varchar(100),
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE users (
  id        int AUTO_INCREMENT NOT NULL,
  email     varchar(250) NOT NULL,
  password  varchar(500) NOT NULL,
  is_admin  tinyint(1) DEFAULT '0',
  blocked   tinyint(1) DEFAULT '0',
  created   timestamp DEFAULT CURRENT_TIMESTAMP,
  name      varchar(250),
  PRIMARY KEY (id)
) ENGINE = InnoDB;

/* Indexes */
CREATE INDEX fk_answers2question_id_idx
  ON answers
  (question_id);

CREATE INDEX api_keys_index02
  ON api_keys
  (user_id);

CREATE INDEX fk_questions2category_id_idx
  ON questions
  (category_id);

CREATE INDEX fk_questions2stack_id_idx
  ON questions
  (stack_id);

CREATE INDEX fk_ratings2question_id_idx
  ON ratings
  (question_id);

CREATE INDEX fk_ratings2user_id_idx
  ON ratings
  (user_id);

CREATE INDEX fk_stacks2user_id_idx
  ON stacks
  (user_id);

CREATE UNIQUE INDEX trash_mail_providers_index02
  ON trash_mail_providers
  (address);

CREATE UNIQUE INDEX email
  ON users
  (email);

/* Foreign Keys */
ALTER TABLE answers
  ADD CONSTRAINT fk_answers2question_id
  FOREIGN KEY (question_id)
    REFERENCES questions(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE api_keys
  ADD CONSTRAINT fk_api_keys2users
  FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE questions
  ADD CONSTRAINT fk_questions2category_id
  FOREIGN KEY (category_id)
    REFERENCES categories(id)
    ON DELETE SET NULL
    ON UPDATE SET NULL;

ALTER TABLE questions
  ADD CONSTRAINT fk_questions2stack_id
  FOREIGN KEY (stack_id)
    REFERENCES stacks(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE ratings
  ADD CONSTRAINT fk_ratings2question_id
  FOREIGN KEY (question_id)
    REFERENCES questions(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE ratings
  ADD CONSTRAINT fk_ratings2user_id
  FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE stacks
  ADD CONSTRAINT fk_stacks2user_id
  FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

/* Data for table "answers" */
INSERT INTO answers (id, `text`, question_id, created) VALUES
  (1, 'yxcvyxcvxycvxycvxcvxcyvxcvxyv', 1, '2013-11-13 11:22:13'),
  (2, 'afsdvxcvxcyvxcvxveedfsdfasdfsfsfeQWEW!\"\"', 1, '2013-11-13 11:22:34');


/* Data for table "api_keys" */
INSERT INTO api_keys (id, api_key, blocked, valid_until, current_monthly_requests, max_monthly_requests, created, user_id, app_name, app_link) VALUES
  (34, 'b910d053fb3973b27388a96f28b4b7e7413e4d66', 0, '2013-12-06 12:51:20', 38, 10000, '2013-10-30 17:10:22', 2, 'asdd', 'asdad');


/* Data for table "api_settings" */
INSERT INTO api_settings (id, max_requests, valid_for) VALUES
  (1, 10000, 3650);


/* Data for table "categories" */
INSERT INTO categories (id, name, visible, description, created) VALUES
  (1, 'asdad', 1, 'adsdas', NULL),
  (2, 'dfg', 1, 'fgd', '2013-11-13 10:47:41'),
  (3, '768768', 0, 'gfjhgfhdhdfghgdh', '2013-11-13 10:47:53');


/* Data for table "questions" */
INSERT INTO questions (id, public, name, blocked, stack_id, category_id, rating, created, rating_count, rating_sum) VALUES
  (1, 1, 'kljikljklj', 0, 2, NULL, 0, '2013-10-29 16:04:35', 0, 0),
  (2, 1, 'jklöjklök', 0, 2, NULL, 0, '2013-10-29 16:04:41', 0, 0);


/* Data for table "ratings" */


/* Data for table "stacks" */
INSERT INTO stacks (id, name, description, user_id, created, public, publickey) VALUES
  (1, '890ß890098', '', 2, '2013-10-29 16:01:35', 0, NULL),
  (2, 'retertret', '', 2, '2013-10-29 16:03:42', 0, 'wVB1KiN7'),
  (3, 'dfgdf', 'gdhhhd', 2, '2013-10-31 11:33:27', 0, NULL);


/* Data for table "trash_mail_providers" */
INSERT INTO trash_mail_providers (id, address) VALUES
  (1, 'asdad');


/* Data for table "users" */
INSERT INTO users (id, email, password, is_admin, blocked, created, name) VALUES
  (2, 'abc@byom.de', '7c4a8d09ca3762af61e59520943dc26494f8941b', 1, 0, '2013-10-28 14:14:27', 'asdad');
